# Generated by Django 3.0.9 on 2020-08-05 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_auto_20200804_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Status',
            new_name='SurveyStatus',
        ),
    ]
