# Generated by Django 3.0.9 on 2020-08-21 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_auto_20200819_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys.Question'),
            preserve_default=False,
        ),
    ]
