# Generated by Django 3.0.9 on 2020-08-24 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20200820_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='responder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responded_surveys', to=settings.AUTH_USER_MODEL),
        ),
    ]
