# Generated by Django 3.0.9 on 2020-08-25 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0009_auto_20200823_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='survey_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.SurveyResponse'),
        ),
    ]
